### ISSUE TITLE
Extract MES data into collections

### ISSUE THREAD

**Issue by corradolicata** [johnjiangrui/johnjiangrui.github.io#3]
BatchID#1 in extract list is not complete
BatchID#3 in extract list is not complete (e.g. time out of furnace is not reported from mes-raw to mes-extract)
BatchID#6 from raw to extract it is missing records

**Comment by johnjiangrui** [comment]
found cause: in dictionary, last 5 English translation words with space, which caused English key error when translate the Chinese key into English. Fixed this by replace space with _
Extracted again, need verification

**Comment by corradolicata** [comment]
BatchID#1 query now shows correct fields and values
BatchID#3 in extract list is now complete
BatchID#6 is now correct in extract

**Comment by corradolicata** [comment]
I extracted this morning at 9:20 am. The batchID#6 are again incomplete in extract, while they are complete in raw.
Check please mes_1669511901000.json on Minguang workstation desktop (all records from Sun 27 Nov 9:20 am till Mon 28 9:20 am.
All other batchID are correct.
